In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
type(a)

numpy.ndarray

In [5]:
b = np.array(([1,2,3,4],[6,7,8,9]))

In [6]:
b

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [7]:
c=np.array((([1,2,3],[4,5,6],[7,8,9])))

In [20]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.array([1.2, 2.3, 3.4, 4.5])

array([1.2, 2.3, 3.4, 4.5])

In [10]:
np.array([1.2,3, 4, 5])

array([1.2, 3. , 4. , 5. ])

In [11]:
np.array([1,2,3,4],dtype ='float64')

array([1., 2., 3., 4.])

In [12]:
np.random.randint(1,10)

1

In [13]:
np.random.rand(5,5)

array([[0.91083517, 0.08322052, 0.68681748, 0.70495039, 0.2178373 ],
       [0.14296899, 0.37497849, 0.70792238, 0.26759682, 0.05969507],
       [0.83574873, 0.47144712, 0.82906285, 0.49984173, 0.79065702],
       [0.02264804, 0.47620506, 0.45837277, 0.5153016 , 0.65380569],
       [0.8932834 , 0.61752908, 0.60700296, 0.90144674, 0.70333197]])

In [14]:
np.zeros(10,dtype='int64')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [15]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.full(([6,7]),10)


array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

In [18]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [19]:
np.random.normal(3,9,)

-2.642083198961486