### Numpy Tutorials
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python



### What is an array
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type





In [8]:
import numpy as np
my_lst=[1,2,3,4,5]



In [9]:
arr=np.array(my_lst)
print(arr)


[1 2 3 4 5]


In [10]:
type(arr)

numpy.ndarray

In [11]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]


In [12]:
arr1=np.array([my_lst1,my_lst2,my_lst3])
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [13]:
type(arr1)

numpy.ndarray

In [14]:
arr1.shape

(3, 5)

In [15]:
##Indexing
## Accessing the array elements
arr[3]

4

In [16]:
arr1[1:,:2]

array([[2, 3],
       [9, 7]])

In [17]:
arr1[:,3:]

array([[4, 5],
       [5, 6],
       [8, 9]])

In [18]:
arr[3:]=100
arr


array([  1,   2,   3, 100, 100])

In [20]:
arr[arr<3]

array([1, 2])

In [21]:
## Create arrays and reshape

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [22]:
arr1=np.arange(0,10).reshape(2,5)
arr2=np.arange(0,10).reshape(2,5)
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [23]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
## random distribution
np.random.rand(3,3)

array([[0.72329992, 0.91007059, 0.97281675],
       [0.59277299, 0.79107806, 0.25059244],
       [0.07927921, 0.01354342, 0.76996621]])

In [25]:
arr_ex=np.random.randn(4,4)
arr_ex

array([[-0.29648727, -1.88729117, -0.49516154, -0.53078487],
       [-0.98395195,  0.35855701,  1.65944442,  0.41720449],
       [-1.50781589, -0.12548953,  0.36806196,  1.03944511],
       [ 0.38785295,  0.06808236,  0.65806868,  0.11804033]])

In [26]:
import seaborn as sns

In [27]:
np.random.randint(0,100,8).reshape(4,2)

array([[30, 74],
       [52,  9],
       [ 0, 82],
       [54, 85]])

In [28]:
np.random.random_sample((1,5))

array([[0.64878346, 0.93802742, 0.61059745, 0.01003481, 0.97793599]])