### numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.2'

In [3]:
a=np.array([3,4,5,6])

In [4]:
a

array([3, 4, 5, 6])

In [5]:
type(a)

numpy.ndarray

In [6]:
s=np.array([4.4,5,6,78])

In [7]:
s

array([ 4.4,  5. ,  6. , 78. ])

In [8]:
p=np.array(s,dtype=int)

In [9]:
p

array([ 4,  5,  6, 78])

In [10]:
n=np.array([range(i,i+4) for i in [3,6,8]])

In [11]:
n

array([[ 3,  4,  5,  6],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11]])

In [12]:
j=np.arange(1,44,3)
j

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43])

In [13]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [2]:
import numpy as np

In [6]:
np.ones((3,3),dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.full((4,5),66)

array([[66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66]])

In [8]:
np.linspace(4,88,7)

array([ 4., 18., 32., 46., 60., 74., 88.])

In [13]:
np.random.random((3,3))

array([[0.40350819, 0.04387513, 0.50273489],
       [0.08236372, 0.2545135 , 0.96852005],
       [0.71868413, 0.34840182, 0.11771194]])

In [14]:
np.random.normal(3,9,(4,4))

array([[ 32.34003683,   2.96705275,   8.62094856,   3.22497905],
       [ -0.24819049,  -9.66268244,  -4.75512337,   2.80250015],
       [ 15.05818299, -10.76396166,  17.86577593, -16.87993363],
       [  4.50279019,   8.19945019,  -6.85179011,  10.68987951]])

In [16]:
np.random.randint(4,7,(2,3))

array([[5, 4, 6],
       [5, 4, 5]])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.empty((3,3))

array([[0.40350819, 0.04387513, 0.50273489],
       [0.08236372, 0.2545135 , 0.96852005],
       [0.71868413, 0.34840182, 0.11771194]])

## NumPy Array Attributes

First let's discuss some useful array attributes. We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array. We'll use NumPy's random number generator, which we will seed with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [22]:
np.random.seed(2)

In [2]:
import numpy as np

In [3]:
x1=np.random.randint(6,size=5)
x2=np.random.randint(3,9,size=(3,3))
x3=np.random.randint(1,7,size=(2,2,3))

In [4]:
x1

array([0, 5, 4, 3, 4])

In [5]:
x2

array([[8, 3, 5],
       [5, 3, 3],
       [7, 7, 8]])

In [6]:
x3

array([[[5, 1, 2],
        [1, 4, 1]],

       [[3, 4, 2],
        [4, 3, 6]]])

In [7]:
def information(x):
    print("demension is :" ,x.ndim)
    print("shape is :", x.shape)
    print("The size is :", x.size)
    print("dtype:", x.dtype)
    print("itemsize:", x.itemsize, "bytes")
    print("nbytes:", x.nbytes, "bytes")

In [32]:
information(x1)

demension is : 1
shape is : (5,)
The size is : 5
dtype: int32
itemsize: 4 bytes
nbytes: 20 bytes


In [33]:
information(x2)

demension is : 2
shape is : (3, 3)
The size is : 9
dtype: int32
itemsize: 4 bytes
nbytes: 36 bytes


In [34]:
information(x3)

demension is : 3
shape is : (2, 2, 3)
The size is : 12
dtype: int32
itemsize: 4 bytes
nbytes: 48 bytes


## Array Indexing: Accessing Single Elements 

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar. In a one-dimensional array, the 𝑖 𝑡ℎ  
ith
 value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [35]:
x1

array([0, 5, 0, 3, 2])

In [37]:
x1[0]

0

In [39]:
x1[-1]

2

In [40]:
x1[-3]

0

In [41]:
x2

array([[6, 3, 5],
       [4, 6, 8],
       [5, 7, 7]])

In [42]:
x2[2]

array([5, 7, 7])

In [43]:
x2[1,1]

6

In [44]:
x2[2][2]

7

In [45]:
x2[:][2]

array([5, 7, 7])

In [46]:
x2[:,1]

array([3, 6, 7])

In [47]:
x3

array([[[5, 6, 4],
        [5, 3, 4]],

       [[4, 3, 2],
        [3, 5, 4]]])

In [48]:
x3[0,1,1]

3

In [56]:
x3[1,0,2]

2

## Array Slicing: Accessing Subarrays¶

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon (:) character. The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array x, use this:
x[start:stop:step]

If any of these are unspecified, they default to the values start=0, stop=size of dimension, step=1. We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.


### One-dimensional subarrays

In [57]:
x=np.arange(10)

In [58]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
x[3:6]

array([3, 4, 5])

In [62]:
x[5:]

array([5, 6, 7, 8, 9])

In [63]:
x[:3]

array([0, 1, 2])

In [66]:
x[1::2]

array([1, 3, 5, 7, 9])

In [68]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [69]:
x[5::-2]

array([5, 3, 1])

### Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas. For example:


In [8]:
x2

array([[8, 3, 5],
       [5, 3, 3],
       [7, 7, 8]])

In [9]:
x2[:2,:3]

array([[8, 3, 5],
       [5, 3, 3]])

In [11]:
x2[::-1,::-1]

array([[8, 7, 7],
       [3, 3, 5],
       [5, 3, 8]])

In [12]:
x2[:3,0]

array([8, 5, 7])

In [13]:
x2[0,:2]

array([8, 3])

In [14]:
x2[0]

array([8, 3, 5])

In [15]:
sub_part=x2[:2,:2]
print(sub_part)

[[8 3]
 [5 3]]


In [16]:
sub_part[0,0]=100

In [17]:
print(sub_part)

[[100   3]
 [  5   3]]


In [18]:
x2 #without using copy creating new variable and chenge some value the effect are shows by orignal data

array([[100,   3,   5],
       [  5,   3,   3],
       [  7,   7,   8]])

In [19]:
##using copy insert or change any variable value the not change value in the orignal dataset
x2_copy=x2[:2,:2].copy()
print(x2_copy)

[[100   3]
 [  5   3]]


In [20]:
x2_copy[0,0]=15

In [21]:
print(x2_copy)

[[15  3]
 [ 5  3]]


In [22]:
x2

array([[100,   3,   5],
       [  5,   3,   3],
       [  7,   7,   8]])

### reshaping

In [10]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [11]:
abc=np.arange(1,10).reshape(3,3)
abc

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
a=np.array([1,2,3])

In [13]:
a.reshape(1,3)

array([[1, 2, 3]])

In [14]:
a.reshape(3,1)

array([[1],
       [2],
       [3]])

In [15]:
a[:2,np.newaxis]

array([[1],
       [2]])

In [16]:
a[np.newaxis,:2]

array([[1, 2]])

In [17]:
b=np.array([4,5,6])
c=np.array([7,8,9])
con=np.concatenate([a,b])
print(con)

[1 2 3 4 5 6]


In [18]:
con1=np.concatenate([a,b,c])

In [19]:
con1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.hstack([abc,abc])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.concatenate([abc,abc],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [24]:
np.vstack([abc,abc])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
np.hstack([abc,abc])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [26]:
abc11=np.arange(16).reshape(4,4)

In [27]:
abc11

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
upper,lower=np.vsplit(abc11,[3])

In [29]:
print(upper)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [30]:
upper1,lower1=np.vsplit(abc11,[2])

In [31]:
print(upper1)

[[0 1 2 3]
 [4 5 6 7]]


In [32]:
print(lower1)

[[ 8  9 10 11]
 [12 13 14 15]]


In [33]:
right,left=np.hsplit(abc11,[2])

In [34]:
right

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [35]:
print(left)

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [36]:
right1,left=np.hsplit(abc11,[3])

In [37]:
right1

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

### Computation on NumPy Arrays: Universal Function

Up until now, we have been discussing some of the basic nuts and bolts of NumPy; in the next few sections, we will dive into the reasons that NumPy is so important in the Python data science world. Namely, it provides an easy and flexible interface to optimized computation with arrays of data.

Computation on NumPy arrays can be very fast, or it can be very slow. The key to making it fast is to use vectorized operations, generally implemented through NumPy's universal functions (ufuncs). This section motivates the need for NumPy's ufuncs, which can be used to make repeated calculations on array elements much more efficient. It then introduces many of the most common and useful arithmetic ufuncs available in the NumPy package.


In [1]:
import numpy as np
np.random.seed(0)

# #Seed function is used to save the state of a random function, 
# so that it can generate same random numbers on multiple executions of 
# the code on the same machine or on different machines (for a specific seed value).
# The seed value is the previous value number generated by the generator. 
# For the first time when there is no previous value, it uses current system time.

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [2]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

3.43 s ± 586 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [4]:
%timeit (1.0 / big_array)

7.06 ms ± 201 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Array arithmetic

In [5]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [6]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [7]:
np.add(x, 2)

array([2, 3, 4, 5])

The following table lists the arithmetic operators implemented in NumPy:


Operator

Equivalent ufunc

Description


+ np.add Addition (e.g., 1 + 1 = 2) 
- np.subtract Subtraction (e.g., 3 - 2 = 1) 
- np.negative Unary negation (e.g., -2) 
* np.multiply Multiplication (e.g., 2 * 3 = 6) 
/ np.divide Division (e.g., 3 / 2 = 1.5) 
// np.floor_divide Floor division (e.g., 3 // 2 = 1) 
** np.power Exponentiation (e.g., 2 ** 3 = 8) 
% np.mod Modulus/remainder (e.g., 9 % 4 = 1) 

Additionally there are Boolean/bitwise operators; we will explore these in Comparisons, Masks, and Boolean Logic.


### Absolute value

In [8]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [9]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [10]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [11]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

### Trigonometric functions


In [13]:
theta = np.linspace(0, np.pi, 3)
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


### Exponents and logarithms

In [14]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]
